import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import P5Canvas from "../components/P5";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>{/* footer component */}</footer>
    </div>
  );
}
